spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  #create: 애플리케이션 실행 시점에 테이블 drop하고 다시 생성   #none: 원래 쓰던 테이블 그대로 재사용
    properties:
      hibernate:
        generate_statistics: true
        #show_sql: true            #-> System.out
        format_sql: true
        default_batch_fetch_size: 100    #지연 로딩 성능 최적화(100~1000 사이), "IN 쿼리로 설정해서 쿼리 적게 나감!" (글로벌 설정), @BatchSize(지역 설정)
    open-in-view: true

logging:
  level:
    #    org.hibernate: debug
    #    org.hibernate.stat: debug
    org.hibernate.SQL: debug       #->logger
    org.hibernate.type: trace      #쿼리 파라미터 로그 남기기